{
 "title": "Imperva Performance Gateway",
 "description": "imperva, gateway, hades",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gateway",
    "label": "Gateway",
    "query": "SHOW TAG VALUES FROM imperva_gw_hades WITH KEY=gatewayname"
   },
   {
    "name": "int",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM imperva_gw_net WITH KEY=interface"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "content": "<img src=https://www.imperva.com/wp-content/uploads/2018/12/logo.svg><br>\n<h3 >Gateway Overview </h3>\n"
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "deckbytes", "label": "RAM Usage in GB" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "query": "SELECT last(\"mem_total\") * (last(\"mem_used\")) / 10000000000 * 1024 FROM \"imperva_gw_sys\" WHERE (\"gatewayname\" =~ /^$gateway$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mem_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "Swap Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "swap_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /boot",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_gw_disk\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"volume\" = '/boot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /data",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_gw_disk\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"volume\" = '/data') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /var",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_gw_disk\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"volume\" = '/var') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Kbps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "kbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Kbps Application",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "alias": "Kbps Application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "kbps_application" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "connection_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Hits/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "http_hits_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Events/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "sql_hits_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Audit Phase 2 Events/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "sql_audit_phase2_events_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Statistics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Events Per Sec" }
   ],
   "targets": [
    {
     "alias": "Threshold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "gw_supported_hps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "SQL Hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "sql_hits_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "SQL Audit P2 Events",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "sql_audit_phase2_events_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Application",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Kbits", "label": "Application Traffic" }
   ],
   "targets": [
    {
     "alias": "Threshold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "gw_supported_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "Application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "kbps_application" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Kbps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Kbits", "label": "Worker Kbps" }
   ],
   "targets": [
    {
     "alias": "Worker #$tag_worker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_workers",
     "query": "SELECT last(\"worker_kbps\") FROM \"imperva_gw_workers\" WHERE (\"gatewayname\" =~ /^$gateway$/) AND $timeFilter GROUP BY time($__interval), \"worker\" fill(none)",
     "select": [
      [
       { "params": [ "worker_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Packets/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Packets/Sec" }
   ],
   "targets": [
    {
     "alias": "Worker #$tag_worker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_workers",
     "select": [
      [
       { "params": [ "worker_packets_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "alias": "Worker #$tag_worker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_workers",
     "select": [
      [
       { "params": [ "worker_queue_length" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  { "title": "Network Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "int" },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bps", "label": "bits out - / bits in +" }
   ],
   "targets": [
    {
     "alias": "$tag_interface in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"),1m) /8 FROM \"imperva_gw_net\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"interface\" =~ /^$int$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$int$/" }
     ]
    },
    {
     "alias": "$tag_interface out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"),1m) /-8 FROM \"imperva_gw_net\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"interface\" =~ /^$int$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$int$/" }
     ]
    }
   ]
  }
 ]
}