{
 "title": "MX Network Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mx",
    "label": "MX",
    "query": "SHOW TAG VALUES FROM imperva_mx_net WITH KEY=mxname"
   },
   {
    "name": "int",
    "label": "Interface",
    "query": "SHOW TAG VALUES FROM imperva_mx_net WITH KEY=interface"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 20, "w": 4, "x": 0, "y": 0 },
   "content": "![imperva-logo](https://www.imperva.com/wp-content/uploads/2018/12/logo.svg)\n#### Performance Metrics \n-----------\n###### [Enterprise Summary](/d/OK-WTZ6Wz/enterprise-summary?orgId=1)\n-----------\n###### [MX Summary](/d/_eEaFY6Wk/mx-summary?orgId=1)\n* [CPU](/d/vqWfBYeZk/mx-cpu-statistics?orgId=1)\n* [Network](/d/1-yxmUeWz/mx-network-statistics?orgId=1  )\n-----------\n###### [Gateway Summary](/d/uQkMDV6Wk/gateway-summary?orgId=1)\n* [CPU](/d/pkJsdV6Wk/gateway-cpu-statistics?orgId=1)\n* [Network](/d/T7e3cV6Wz/gateway-network-statistics?orgId=1)\n* [Statistics](/d/YBW_BwnMk/gateway-statistics?orgId=1)\n-----------\n###### [Agent Summary](/d/kn0syVeWz/agent-summary?orgId=1)\n-----------\n###### [Server Groups](/d/3lfMdYeWk/server-groups?orgId=1)\n-----------\n###### [Audit Policies Summary](/d/bM-4JleZz/audit-policies-summary?orgId=1)  \n\n"
  },
  {
   "title": "Appliance Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_mx_sys",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mxname", "operator": "=~", "value": "/^$mx$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Bytes  - In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"),5m) FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Bytes  - Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"),5m) FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Packets  - In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"rx_packets\"),5m) FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Packets  - Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tx_packets\"),5m) FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bytes  - In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"rx_bytes\") FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bytes  - Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"tx_bytes\") FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Packets  - In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"rx_packets\") FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Packets  - Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"tx_packets\") FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - All Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes out - / bytes in +" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"),5m) FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"),5m) FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Packets - All Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "packets out - / packets in +" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_packets\"),5m)FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tx_packets\"),5m)FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Individual Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "int" },
  {
   "title": "Sockets - All Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "packets out - / packets in +" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_net",
     "query": "SELECT non_negative_derivative(mean(\"sockets\"),5m)FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - $int",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes out - / bytes in +" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"),5m) FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/ AND \"interface\" =~ /^$int$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"),5m) FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/ AND \"interface\" =~ /^$int$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Packets - $int",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "packets out - / packets in +" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_packets\"),5m)FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/ AND \"interface\" =~ /^$int$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tx_packets\"),5m)FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/ AND \"interface\" =~ /^$int$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sockets - $int",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "packets out - / packets in +" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_net",
     "query": "SELECT non_negative_derivative(mean(\"sockets\"),5m)FROM \"imperva_mx_net\" WHERE (\"mxname\" =~ /^$mx$/ AND \"interface\" =~ /^$int$/) AND $timeFilter GROUP BY time($__interval), interface fill(none)",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  }
 ]
}