{
 "title": "Gateway Summary",
 "description": "imperva, gateway, hades",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gateway",
    "label": "Gateway",
    "query": "SHOW TAG VALUES FROM imperva_gw_hades WITH KEY=gatewayname"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 20, "w": 4, "x": 0, "y": 0 },
   "content": "![imperva-logo](https://www.imperva.com/wp-content/uploads/2018/12/logo.svg)\n#### Performance Metrics \n-----------\n###### [Enterprise Summary](/d/OK-WTZ6Wz/enterprise-summary?orgId=1)\n-----------\n###### [MX Summary](/d/_eEaFY6Wk/mx-summary?orgId=1)\n* [CPU](/d/vqWfBYeZk/mx-cpu-statistics?orgId=1)\n* [Network](/d/1-yxmUeWz/mx-network-statistics?orgId=1  )\n-----------\n###### [Gateway Summary](/d/uQkMDV6Wk/gateway-summary?orgId=1)\n* [CPU](/d/pkJsdV6Wk/gateway-cpu-statistics?orgId=1)\n* [Network](/d/T7e3cV6Wz/gateway-network-statistics?orgId=1)\n* [Statistics](/d/YBW_BwnMk/gateway-statistics?orgId=1)\n-----------\n###### [Agent Summary](/d/kn0syVeWz/agent-summary?orgId=1)\n-----------\n###### [Server Groups](/d/3lfMdYeWk/server-groups?orgId=1)\n-----------\n###### [Audit Policies Summary](/d/bM-4JleZz/audit-policies-summary?orgId=1)  \n\n"
  },
  {
   "title": "Appliance Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "SAR CPU: All - Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\")+last(\"system\")+last(\"nice\")+last(\"steal\")+last(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "IOwait",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"mem_used\")  / last(\"mem_total\") * 100 FROM \"imperva_gw_sys\" WHERE (\"gatewayname\" =~ /^$gateway$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "query": "SELECT last(\"swap_used\")  / last(\"swap_total\") * 100 FROM \"imperva_gw_sys\" WHERE (\"gatewayname\" =~ /^$gateway$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_gw_disk\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"volume\" = '/') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /boot",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_gw_disk\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"volume\" = '/boot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_gw_disk\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"volume\" = '/data') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /var",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_gw_disk\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"volume\" = '/var') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Applicative Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "Kbits", "label": "Application Traffic" }
   ],
   "targets": [
    {
     "alias": "Threshold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "gw_supported_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "Application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "kbps_application" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Kbps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 17 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "kbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Kbps Application",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 17 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "alias": "Kbps Application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "kbps_application" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Hits/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "http_hits_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "connection_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Statistics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Events Per Sec" }
   ],
   "targets": [
    {
     "alias": "Threshold",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "gw_supported_hps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "SQL Hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "sql_hits_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    },
    {
     "alias": "SQL Audit P2 Events",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "sql_audit_phase2_events_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Events/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 4, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "sql_hits_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Audit Phase 2 Events/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_hades",
     "select": [
      [
       { "params": [ "sql_audit_phase2_events_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Kbps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 30 },
   "yaxes": [
    { "format": "Kbits", "label": "Worker Kbps" }
   ],
   "targets": [
    {
     "alias": "Worker #$tag_worker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_workers",
     "query": "SELECT last(\"worker_kbps\") FROM \"imperva_gw_workers\" WHERE (\"gatewayname\" =~ /^$gateway$/) AND $timeFilter GROUP BY time($__interval), \"worker\" fill(none)",
     "select": [
      [
       { "params": [ "worker_kbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Packets/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Packets/Sec" }
   ],
   "targets": [
    {
     "alias": "Worker #$tag_worker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_workers",
     "select": [
      [
       { "params": [ "worker_packets_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "alias": "Worker #$tag_worker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_workers",
     "select": [
      [
       { "params": [ "worker_queue_length" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 3, "x": 18, "y": 36 }, "content": "\n\n\n\n\n" }
 ]
}