{
 "title": "Gateway CPU Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gateway",
    "label": "Gateway",
    "query": "SHOW TAG VALUES FROM imperva_gw_hades WITH KEY=gatewayname"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM imperva_gw_sar_cpu WITH KEY=cpu"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 20, "w": 4, "x": 0, "y": 0 },
   "content": "![imperva-logo](https://www.imperva.com/wp-content/uploads/2018/12/logo.svg)\n#### Performance Metrics \n-----------\n###### [Enterprise Summary](/d/OK-WTZ6Wz/enterprise-summary?orgId=1)\n-----------\n###### [MX Summary](/d/_eEaFY6Wk/mx-summary?orgId=1)\n* [CPU](/d/vqWfBYeZk/mx-cpu-statistics?orgId=1)\n* [Network](/d/1-yxmUeWz/mx-network-statistics?orgId=1  )\n-----------\n###### [Gateway Summary](/d/uQkMDV6Wk/gateway-summary?orgId=1)\n* [CPU](/d/pkJsdV6Wk/gateway-cpu-statistics?orgId=1)\n* [Network](/d/T7e3cV6Wz/gateway-network-statistics?orgId=1)\n* [Statistics](/d/YBW_BwnMk/gateway-statistics?orgId=1)\n-----------\n###### [Agent Summary](/d/kn0syVeWz/agent-summary?orgId=1)\n-----------\n###### [Server Groups](/d/3lfMdYeWk/server-groups?orgId=1)\n-----------\n###### [Audit Policies Summary](/d/bM-4JleZz/audit-policies-summary?orgId=1)  \n\n"
  },
  {
   "title": "SAR CPU: All - Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\")+last(\"system\")+last(\"nice\")+last(\"steal\")+last(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Appliance Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "SAR CPU: All - Idle",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"idle\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load: All - Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"load\") FROM \"imperva_gw_cpuload\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "SAR CPU: All - System",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"system\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "SAR CPU: All - User",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "SAR CPU: All - IOwait",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "SAR CPU: All - Nice",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"nice\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "SAR CPU: All - Steal",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"steal\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  { "title": "Individual CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "cpu" },
  {
   "title": "GW SAR CPU Utilization - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on the command \"sar -P ALL 0\".",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\")+last(\"system\")+last(\"nice\")+last(\"steal\")+last(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" =~  /^$cpu$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "io_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  {
   "title": "GW CPU Load - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on info from /proc/hades/cpuload.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "CPU Load" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_cpuload",
     "query": "SELECT mean(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval), \"cpu\" fill(none)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  {
   "title": "GW TOP CPU Utilization - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on the command \"sar -P ALL 0\".",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"wait\")+last(\"system\")+last(\"nice\")+last(\"steal_time\")+last(\"user\") FROM \"imperva_gw_top_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" =~  /^$cpu$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "io_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  { "title": "Individual CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "GW SAR CPU Utilization - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on the command \"sar -P ALL 0\".",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\")+last(\"system\")+last(\"nice\")+last(\"steal\")+last(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" =~  /^$cpu$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "io_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  {
   "title": "GW CPU Load - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on info from /proc/hades/cpuload.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "percent", "label": "CPU Load" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_cpuload",
     "query": "SELECT mean(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval), \"cpu\" fill(none)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  {
   "title": "GW TOP CPU Utilization - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on the command \"sar -P ALL 0\".",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"wait\")+last(\"system\")+last(\"nice\")+last(\"steal_time\")+last(\"user\") FROM \"imperva_gw_top_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" =~  /^$cpu$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "io_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  { "title": "Individual CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "GW SAR CPU Utilization - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on the command \"sar -P ALL 0\".",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\")+last(\"system\")+last(\"nice\")+last(\"steal\")+last(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" =~  /^$cpu$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "io_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  {
   "title": "GW CPU Load - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on info from /proc/hades/cpuload.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "percent", "label": "CPU Load" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_cpuload",
     "query": "SELECT mean(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval), \"cpu\" fill(none)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  {
   "title": "GW TOP CPU Utilization - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on the command \"sar -P ALL 0\".",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"wait\")+last(\"system\")+last(\"nice\")+last(\"steal_time\")+last(\"user\") FROM \"imperva_gw_top_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" =~  /^$cpu$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "io_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  { "title": "Individual CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "GW SAR CPU Utilization - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on the command \"sar -P ALL 0\".",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\")+last(\"system\")+last(\"nice\")+last(\"steal\")+last(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" =~  /^$cpu$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "io_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  {
   "title": "GW CPU Load - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on info from /proc/hades/cpuload.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "percent", "label": "CPU Load" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_cpuload",
     "query": "SELECT mean(\"user\") FROM \"imperva_gw_sar_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval), \"cpu\" fill(none)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  },
  {
   "title": "GW TOP CPU Utilization - CPU: $cpu",
   "type": "graph",
   "description": "Utilization based on the command \"sar -P ALL 0\".",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU: $cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"wait\")+last(\"system\")+last(\"nice\")+last(\"steal_time\")+last(\"user\") FROM \"imperva_gw_top_cpu\" WHERE (\"gatewayname\" =~ /^$gateway$/ AND \"cpu\" =~  /^$cpu$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "io_wait" ], "type": "alias" }
      ],
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  }
 ]
}