{
 "title": "MX Summary",
 "description": "imperva, gateway, hades",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mx",
    "label": "MX",
    "query": "SHOW TAG VALUES FROM imperva_mx_sys WITH KEY=mxname"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 20, "w": 4, "x": 0, "y": 0 },
   "content": "![imperva-logo](https://www.imperva.com/wp-content/uploads/2018/12/logo.svg)\n#### Performance Metrics \n-----------\n###### [Enterprise Summary](/d/OK-WTZ6Wz/enterprise-summary?orgId=1)\n-----------\n###### [MX Summary](/d/_eEaFY6Wk/mx-summary?orgId=1)\n* [CPU](/d/vqWfBYeZk/mx-cpu-statistics?orgId=1)\n* [Network](/d/1-yxmUeWz/mx-network-statistics?orgId=1  )\n-----------\n###### [Gateway Summary](/d/uQkMDV6Wk/gateway-summary?orgId=1)\n* [CPU](/d/pkJsdV6Wk/gateway-cpu-statistics?orgId=1)\n* [Network](/d/T7e3cV6Wz/gateway-network-statistics?orgId=1)\n* [Statistics](/d/YBW_BwnMk/gateway-statistics?orgId=1)\n-----------\n###### [Agent Summary](/d/kn0syVeWz/agent-summary?orgId=1)\n-----------\n###### [Server Groups](/d/3lfMdYeWk/server-groups?orgId=1)\n-----------\n###### [Audit Policies Summary](/d/bM-4JleZz/audit-policies-summary?orgId=1)  \n\n"
  },
  {
   "title": "Appliance Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_mx_sys",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mxname", "operator": "=~", "value": "/^$mx$/" }
     ]
    }
   ]
  },
  {
   "title": "SAR CPU: All - Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\")+last(\"system\")+last(\"nice\")+last(\"steal\")+last(\"user\") FROM \"imperva_mx_sar_cpu\" WHERE (\"mxname\" =~ /^$mx$/ AND \"cpu\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "IOwait",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"iowait\") FROM \"imperva_mx_sar_cpu\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sar_cpu",
     "query": "SELECT last(\"mem_used\")  / last(\"mem_total\") * 100 FROM \"imperva_mx_sys\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_sys",
     "query": "SELECT last(\"swap_used\")  / last(\"swap_total\") * 100 FROM \"imperva_mx_sys\" WHERE (\"mxname\" =~ /^$mx$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_mx_disk\" WHERE (\"mxname\" =~ /^$mx$/ AND \"volume\" = '/') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /boot",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_mx_disk\" WHERE (\"mxname\" =~ /^$mx$/ AND \"volume\" = '/boot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /sys",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_mx_disk\" WHERE (\"mxname\" =~ /^$mx$/ AND \"volume\" = '/sys') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - /var",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_gw_disk",
     "query": "SELECT last(\"disk_used\" ) /4 / (\"disk_capacity\" /4) * 100 FROM \"imperva_mx_disk\" WHERE (\"mxname\" =~ /^$mx$/ AND \"volume\" = '/var') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gatewayname", "operator": "=~", "value": "/^$gateway$/" },
      { "condition": "AND", "key": "volume", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Total Gateways",
   "type": "singlestat",
   "description": "The total number of SecureSphere gateways associated with this management server (MX).",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_mx",
     "select": [
      [
       { "params": [ "total_gateways" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total_gateways" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "mxname", "operator": "=~", "value": "/^$mx$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Agents",
   "type": "singlestat",
   "description": "The total number of agents registered to the gateways associated with this management server (MX).",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_mx",
     "select": [
      [
       { "params": [ "total_agents" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total_agents" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "mxname", "operator": "=~", "value": "/^$mx$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Protected IPs",
   "type": "singlestat",
   "description": "The total number of protected IP addresses associated with this management server (MX).",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_mx",
     "select": [
      [
       { "params": [ "total_protected_ips" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total_protected_ips" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "mxname", "operator": "=~", "value": "/^$mx$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Server Groups",
   "type": "singlestat",
   "description": "The total number of server groups associated with this management server (MX).",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "imperva_mx",
     "select": [
      [
       { "params": [ "total_server_groups" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total_server_groups" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "mxname", "operator": "=~", "value": "/^$mx$/" }
     ]
    }
   ]
  }
 ]
}